name: Catalog Service

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - 'catalog-service/**'
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper Executable
        working-directory: ${{env.working-directory}}
        run: chmod +x ./mvnw

      - name: Build with Maven
        working-directory: ${{env.working-directory}}
        run: ./mvnw verify
        
